"""Explicit current TwelveLabs Models API routes, separate from external MCP names."""

ROUTES = {
    'asset_create': ('POST', '/v1.3/assets', 'multipart/form-data'),
    'asset_get': ('GET', '/v1.3/assets/{asset_id}', 'none'),
    'asset_list': ('GET', '/v1.3/assets', 'query'),
    'asset_delete': ('DELETE', '/v1.3/assets/{asset_id}', 'query'),
    'index_create': ('POST', '/v1.3/indexes', 'application/json'),
    'index_list': ('GET', '/v1.3/indexes', 'query'),
    'index_delete': ('DELETE', '/v1.3/indexes/{index_id}', 'none'),
    'indexed_asset_create': ('POST', '/v1.3/indexes/{index_id}/indexed-assets', 'application/json'),
    'indexed_asset_get': ('GET', '/v1.3/indexes/{index_id}/indexed-assets/{indexed_asset_id}', 'query'),
    'indexed_asset_list': ('GET', '/v1.3/indexes/{index_id}/indexed-assets', 'query'),
    'indexed_asset_delete': ('DELETE', '/v1.3/indexes/{index_id}/indexed-assets/{indexed_asset_id}', 'none'),
    'search_text_image_composed_entity': ('POST', '/v1.3/search', 'multipart/form-data'),
    'embedding_task_create': ('POST', '/v1.3/embed-v2/tasks', 'application/json'),
    'embedding_task_get': ('GET', '/v1.3/embed-v2/tasks/{task_id}', 'none'),
    'embedding_task_list': ('GET', '/v1.3/embed-v2/tasks', 'query'),
    'entity_collection_create': ('POST', '/v1.3/entity-collections', 'application/json'),
    'entity_collection_list': ('GET', '/v1.3/entity-collections', 'query'),
    'entity_collection_delete': ('DELETE', '/v1.3/entity-collections/{collection_id}', 'none'),
    'entity_create': ('POST', '/v1.3/entity-collections/{collection_id}/entities', 'application/json'),
    'entity_list': ('GET', '/v1.3/entity-collections/{collection_id}/entities', 'query'),
    'entity_delete': ('DELETE', '/v1.3/entity-collections/{collection_id}/entities/{entity_id}', 'none'),
    'analysis_sync': ('POST', '/v1.3/analyze', 'application/json'),
    'analysis_task_create': ('POST', '/v1.3/analyze/tasks', 'application/json'),
    'analysis_task_get': ('GET', '/v1.3/analyze/tasks/{task_id}', 'none'),
    'analysis_task_list': ('GET', '/v1.3/analyze/tasks', 'query'),
    'analysis_task_cancel': ('POST', '/v1.3/analyze/tasks/{task_id}/cancel', 'none'),
    'analysis_task_delete': ('DELETE', '/v1.3/analyze/tasks/{task_id}', 'none'),
}
